// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlogEngine.Data.Models
{
    public partial class PostState
    {
        public PostState()
        {
            LogPost = new HashSet<LogPost>();
            Post = new HashSet<Post>();
        }

        public short PostStateId { get; set; }
        public string Description { get; set; }
        public byte State { get; set; }

        public virtual ICollection<LogPost> LogPost { get; set; }
        public virtual ICollection<Post> Post { get; set; }
    }
}