// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlogEngine.Data.Models
{
    public partial class User
    {
        public User()
        {
            LogPost = new HashSet<LogPost>();
            Post = new HashSet<Post>();
        }

        public int UserId { get; set; }
        public short RoleId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public byte State { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<LogPost> LogPost { get; set; }
        public virtual ICollection<Post> Post { get; set; }
    }
}