// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlogEngine.Security.Data.Models
{
    public partial class User
    {
        public int UserId { get; set; }
        public short RoleId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public byte State { get; set; }

        public virtual Role Role { get; set; }
    }
}